services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081"
    restart: unless-stopped
    stdin_open: true
    tty: true
